### ISSUE TITLE
Implement New Orphanet Parser Feature

### ISSUE THREAD

**Issue by themkdemiiir** [cdliproject/Prometheus#2]
The project involves creating a new parser to effectively manage and integrate the comprehensive rare diseases dataset from Orphanet, which is available on their Orphanet Scientific Knowledge Files website. This data is rich in content, including rare disease alignments with various medical classifications like SNOMED CT, ICD-10, ICD-11, OMIM, UMLS, MeSH, MedDRA, and GARD. In addition, it provides detailed information on classifications of rare diseases, their linearisation, associated genes, clinical signs and symptoms, functional consequences, epidemiology, and natural history. We aim to develop a parser to handle these diverse data types and bring them into a unified format that fits our system's needs. This will significantly enhance our capacity to utilize the Orphanet dataset for advanced analysis and application in rare disease studies.

Task Checklist:

- [ ]  Analyze Orphanet's data format and structure to understand integration requirements.
- [ ]  Design the parser architecture, ensuring compatibility with our current system.
- [ ]  Develop the parser code, incorporating necessary features for Orphanet data handling.
- [ ]  Test the parser with sample Orphanet data to validate functionality.
- [ ]  Integrate the parser into the existing system, ensuring seamless data flow.
- [ ]  Conduct thorough unit and integration testing to ensure stability and performance.
- [ ]  Please document the new feature comprehensively and update user manuals accordingly.

The Link:
https://www.orphadata.com/orphanet-scientific-knowledge-files/

**Comment by rekurrenzk** [comment]
Folders are re-factored, and more function-base script's defined. Please re-review the latest update @themkdemiiir

**Comment by rekurrenzk** [comment]
Hello @cdliproject/cdli-core-team,

I have finally perpetuated the H5 file from XML file format, as you can follow up at #11 

**Utility Implementations**

I have discovered that XSD compares the file transformation from XML to H5. Some websites do this for free, such as:
[Free Formater](https://www.freeformatter.com/xsd-generator.html)

However, we might also implement the features by ourselves, using:

[Orphadata Products Description](https://www.orphadata.com/docs/OrphadataFreeAccessProductsDescription.pdf)

I will incorporate XSD validation in our main.py script.
